### ISSUE TITLE
Mentions for roles are the same color as the rest of the selection

### ISSUE THREAD

**Issue by ScarletWolf275** [CapnKitten/Material-Discord#14]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/19330439/41780595-d6cbfec0-763d-11e8-83e3-91a333c67d48.png">
All the roles are the same color as the rest which does not make em stand out

**Comment by CapnKitten** [comment]
I have made the mentioned role a bit brighter, but I find this a bit of a non-issue because the mentioned message has a blue background. It will be in the next update.

Also, for a future reference, please only make 1 issue and include all of the problems in that. There's no need to make 4 issues on small things. Thank you.
