### ISSUE TITLE
weird message outline

### ISSUE THREAD

**Issue by ghoomy** [CapnKitten/Material-Discord#182]
![image](https://user-images.githubusercontent.com/35694451/213888786-f54488d3-d3db-4ece-8921-e47181af271a.png)

**Comment by KTibow** [comment]
cant reproduce, what did you do for this

**Comment by ghoomy** [comment]
literally nothing

**Comment by KTibow** [comment]
as in it just showed up when you opened discord?

**Comment by ghoomy** [comment]
No, it happens when you focus on a message between other messages in the same time-relevant group.

**Comment by KTibow** [comment]
i can't focus on any messages with tab

**Comment by CapnKitten** [comment]
I can't reproduce it either, but I know why it's like that. In order for the message bubbles to work, the starting message is always rounded as if it were a single message. Subsequent messages are then treated as if they're the last message in the group to form the bubble. There's no way to detect if a message is the last one in a group, so previous messages have little carrots added to them and are placed at the bottom to make it look as if it's not rounded.

If you don't understand that because of my poor explanation, it means that the accessibility outline will remain like that unless Discord does an overhaul of how messages appear.
