### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by B4ttery** [CapnKitten/Material-Discord#194]
I don't really know if I should change something but when I   turn on discord dyslexia that changes the font an spacing, with this theme the dyslexic won't work (very good explanation I know I'm sorry)

**Comment by CapnKitten** [comment]
Material Discord uses a different font that overrides everything except the code font. In order to overwrite that with Discord Dyslexia, you'll have to add `--app-font: "OpenDyslexic";` to that theme's root. I've included an image on what it'll look like below.

![image](https://github.com/CapnKitten/Material-Discord/assets/4013216/3c659dd3-43c0-4494-a431-20a9d991e210)
