### ISSUE TITLE
Status selector positioned incorrectly after discord update.

### ISSUE THREAD

**Issue by vmurray1** [CapnKitten/Material-Discord#77]
![image](https://user-images.githubusercontent.com/13809828/76055202-eb648300-5f40-11ea-815c-38ecf4443386.png)

**Comment by CapnKitten** [comment]
Could you open the dev console (CTRL + shift + i) and use the pointer option (red circle) and select any of the status buttons? I need to see the style values in the highlighted line of the dev console below. A screenshot of the dev console will do just fine. In the past, there was an issue with another person having the same problem as you, and turned out that the `left` and `right` values were a bit different. Thanks.

![aG6Te](https://user-images.githubusercontent.com/4013216/76056448-90348f80-5f44-11ea-9842-6289d40e92bd.png)

**Comment by vmurray1** [comment]
![image](https://user-images.githubusercontent.com/13809828/76105733-8a21cb80-5fa3-11ea-82d0-5ab28e219063.png)

**Comment by vmurray1** [comment]
Also worth noting that the behavior of the `bottom` attribute is very inconsistent.

<details>
  <summary>left: 80px; bottom: 63px</summary>
  <img src=https://user-images.githubusercontent.com/13809828/76129682-00d7bc80-5fd6-11ea-8a9f-0c80c8f90a7a.png />
</details>

<details>
  <summary>left: 80px; bottom: 64px </summary>
  <img src=https://user-images.githubusercontent.com/13809828/76129939-e2be8c00-5fd6-11ea-9021-3757f594c9b6.png />
</details>

<details>
  <summary>left: 80px; bottom: 65px </summary>
  <img src=https://user-images.githubusercontent.com/13809828/76130062-61b3c480-5fd7-11ea-8a14-0817d3a5c591.png />
</details>

I can't for the life of me figure out why setting `bottom` to 64px exactly also causes the div to shift 8 pixels to the left and an extra four pixels up.

**Comment by CapnKitten** [comment]
This _should_ be fixed with v2.1.9. If it isn't, please let me know, thanks.
