### ISSUE TITLE
URLs & URL Embeds not respecting --accent-color, and some other requests / options

### ISSUE THREAD

**Issue by sjain882** [CapnKitten/Material-Discord#96]
Hey, thanks for this great theme!

### I noticed some issues:

![image](https://user-images.githubusercontent.com/43217178/85171175-69396980-b266-11ea-975c-4dd4983cdeab.png)

URLs & URL embeds don't seem to respect --accent-color. I am using an orange value for --accent-color:

```
:root {
    --accent-color: #FD905D !important;
    --accent-button-action: #FD905D !important;
    --accent-rgb: #FD905D !important;
    --accent-text-color: #1B1B21 !important;
}
```

Do note, however that it is respected in the chat message box / text input field:

![image](https://user-images.githubusercontent.com/43217178/85171921-e1ecf580-b267-11ea-8bfa-de5b9015cf89.png)

---

Image previews also have out of place buttons, and a weird "user at time" thing in the bottom left, which interferes with the BetterImageViewer plugin.

![image](https://user-images.githubusercontent.com/43217178/85173359-fed6f800-b26a-11ea-8da3-eabfde7a7a5b.png)

However I am not sure if it is caused by a plugin... here are the plugins i am using which might affect this:
- BetterImageViewer v1.3.4
- ImageZoom v1.1.3

![image](https://user-images.githubusercontent.com/43217178/85176284-6001ca00-b271-11ea-9459-b1aa6f1d7e5b.png)

As well as this, these toasts feel more like Material 1, and seem too tall, and inconsistent with the normal ones:

![image](https://user-images.githubusercontent.com/43217178/85176336-832c7980-b271-11ea-9854-8a24a208c769.png)

And for some reason, the "zoom settings" option of the ImageZoom plugin is missing.

---

and im not sure if this is intended, but the hover for the "settings" button in Settings > Plugins highlights the whole plugin element:

![ezgif-3-b59ddb223303](https://user-images.githubusercontent.com/43217178/85173593-7efd5d80-b26b-11ea-92fd-262f8f7e16d0.gif)

some UI elements in plugin settings also seem to be out of place:

![image](https://user-images.githubusercontent.com/43217178/85173687-b1a75600-b26b-11ea-91ed-8e1a1216e57f.png)

![image](https://user-images.githubusercontent.com/43217178/85173854-15ca1a00-b26c-11ea-990e-3b18abec9ddc.png)

![image](https://user-images.githubusercontent.com/43217178/85174117-97ba4300-b26c-11ea-805e-2b37d3a0d71e.png)

### I also had a few requests:

Would it be possible to change the colour of icons like the one in the search button below, just like `--accent-text-color` - The text color for buttons and other various elements with the accent background color. 

The search button:
![image](https://user-images.githubusercontent.com/43217178/85170223-01365380-b265-11ea-8864-f37a1eb90bc4.png)

What I'd like it to be (example of `--accent-text-color`)
![image](https://user-images.githubusercontent.com/43217178/85170580-802b8c00-b265-11ea-988c-05869d2b2229.png)

I also feel that the search button is a little too large, but this may be more of a subjective thing.

---

![image](https://user-images.githubusercontent.com/43217178/85170690-acdfa380-b265-11ea-8ef3-56a026e0be1e.png)

The fullwidth settings may be nice to some but its too big a change from normal discord / other themes for me, would it be possible to implement a toggle / css variable for it? Or, if you'd rather not, a way using custom CSS right now without you having to change the theme's css?

---

![image](https://user-images.githubusercontent.com/43217178/85171026-27a8be80-b266-11ea-9c7c-81b08a7beaba.png)

Personally, I am not a fan of the message bubbles / boxes, and would prefer none / all messages to have the same background colour as the rest of the chat. Would it be possible to implement a toggle / css variable for it? Or, if you'd rather not, a way using custom CSS right now without you having to change the theme's css?

---

![image](https://user-images.githubusercontent.com/43217178/85174801-ffbd5900-b26d-11ea-9bd5-9565d68cffe4.png)

I feel these statuses blend in with the profile pictures too much. Here are the statuses in Nox, which have a really nice trimming thing going on, and is thicker:

![image](https://user-images.githubusercontent.com/43217178/85174789-f6cc8780-b26d-11ea-93ca-4da6035bc242.png)

If its not too much trouble, would you consider implementing this? I know it might be a big ask or change, just wondering. Its mostly down to personal preference.

Thanks so much in advance! Loving the theme - especially the custom icons, google sans font, and regular updates, without having to mess with tempfixes all the time (Nox).

---

edit: one last thing. Is it possible to change the text colour of the channels mentioned in text chat:

![image](https://user-images.githubusercontent.com/43217178/85172943-0ea20c80-b26a-11ea-8fdf-e02a10a4ed11.png)

**Comment by CapnKitten** [comment]
It's impossible to have toggles with CSS alone, so with a lot of what you're asking, would require either the source code being changed or overriding said code in the custom CSS part of BetterDiscord.

___Plugin settings UI___:
There's no uniformity between plugin devs and how they manage their settings UI, so it never looks the same between different plugins. I'll revert it back to vanilla CSS with extremely light CSS editing to make it more manageable.

___Search button___:
That search button icon isn't in the html by default, so it uses a SVG icon encoded to base64 in the `background-image` property to display it. All of that means is that it's a static "image" and can't be changed by a variable like `accent-text-color` in the CSS. Someone else had the same request as you, and I had the explain the same thing to them. I can make it a bit smaller though.

___Full width___:
It's been like that for quite some time (I want to say over a year), so I won't be changing it back to how vanilla Discord is.

___Messages bubble___:
I'm working on making them look like the Material Design 2 chat bubbles. But it'll still be a bubble because that's how it's supposed to look when basing it off of Google's Material Design guidelines.

___Status icons___:
I can put the mask back that'll make it stand out more.

---

As for the bugs, the following will be fixed in the next update:
- Link color
- Plugin list button hover/active effect
- Channel/mention text color will be handled by `--accent-rgb-text-color`

I'll look into the image issue with those plugins enabled.
